backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "landing-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: markdown }
          - {
              label: "Image",
              name: image,
              widget: object,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: "Alt Text", name: alt, widget: string },
                ],
            }
          - {
              label: "Email Capture",
              name: emailCapture,
              widget: object,
              fields: [{ label: Heading, name: heading, widget: string }],
            }
          - {
              label: "Product List",
              name: products,
              widget: list,
              fields:
                [
                  { label: Key, name: key, widget: string },
                  { label: Title, name: title, widget: string },
                  { label: Subtitle, name: subtitle, widget: string },
                  {
                    label: Images,
                    name: images,
                    widget: list,
                    field:
                      {
                        label: Image,
                        name: image,
                        widget: object,
                        fields:
                          [
                            { label: Image, name: image, widget: image },
                            { label: Alt Text, name: alt, widget: string },
                          ],
                      },
                  },
                  { label: THC Content, name: thc, widget: string },
                  { label: CBD Content, name: cbd, widget: string },
                  { label: Terpenes Content, name: terpenes, widget: string },
                  { label: Profile, name: profile, widget: string },
                  { label: Description, name: description, widget: string },
                  { label: Footnote, name: footnote, widget: string },
                ],
            }
